### ISSUE TITLE
TrySmalltalkWidget fails open due to SourceArea being moved to the attic.

### ISSUE THREAD

**Issue by tomrake** [amber-smalltalk/trysmalltalk#13]
While attempting to produce the gh-pages for trysmalltalk I found master 

```
 TrySmalltalkWidget class >> open
boot.js:1022 TrySmalltalkWidget(Widget) >> appendToJQuery:
boot.js:1022 TrySmalltalkWidget >> renderOn:
boot.js:1022 TagBrush >> with:
boot.js:1022 TagBrush >> append:
boot.js:1022 BlockClosure >> appendToBrush:
boot.js:1022 TagBrush >> appendBlock:
boot.js:1022 BlockClosure >> value:
boot.js:1022 a block (in TrySmalltalkWidget >> renderOn:)
boot.js:1022 TrySmalltalkWidget >> workspace
boot.js:1022 UndefinedObject(ProtoObject) >> doesNotUnderstand:
boot.js:1022 nil does not understand #new
```

TrySmalltalk#workspace
```
workspace
	^ workspace ifNil: [
          	workspace := SourceArea new]
```

A possible solution is to move SourceArea class into TrySmalltalk

**Comment by sebastianconcept** [comment]
Ah because SourceArea is part of IDE which is in the attic now.

The fix is to make the attic a dependency (the tutorial has the inspect so the IDE is needed anyway)

**Comment by hhzl** [comment]
See PR #14

**Comment by hhzl** [comment]
PR #14 is not sufficient to fix the issue.

The browser complains with 

        Error: Module name "codemirror/lib/codemirror" has not been loaded yet
        for context: _. Use require([]) http://requirejs.org/docs/errors.html#notloaded the.js:497

**Comment by herby** [comment]
Add amber-attic/IDE into deploy.js.

**Comment by hhzl** [comment]
It is [there](https://github.com/amber-smalltalk/trysmalltalk/blob/master/deploy.js) and still does not work.

**Comment by sebastianconcept** [comment]
May just need a fresh?

`grunt devel`
`grunt deploy`
`grunt`

?

**Comment by herby** [comment]
`grunt` is not needed. `grunt devel` is. On the other hand, who loaded codemirror, other than IDE (which suggests it _was_ run). Strange, really.

Sebastian Sastre <notifications@github.com>napísal/a:

>Mayjustneedafresh?gruntdevelgruntdeploygrunt?ReplytothisemaildirectlyorviewitonGitHub.

**Comment by hhzl** [comment]
As suggested by @sebastianconcept I did a test with ``amber init`` from scratch https://github.com/hhzl/trysmalltalk0142 . (see [README.md](https://github.com/hhzl/trysmalltalk0142/blob/master/README.md) for details how it was done)

Then I checked deployment https://github.com/hhzl/trysmalltalk0142/tree/gh-1 (move of amber-attic in ``deploy.js`` and ``devel.js``)

I still get the error message


    Error: Module name "codemirror/lib/codemirror" has not been loaded yet for context: _. 
    Use require([]) http://requirejs.org/docs/errors.html#notloaded the.js:497

**Comment by herby** [comment]
I just cloned this repo, ran `bower install`, `npm install`, `grunt devel` and `amber serve`. Loaded `http://localhost:4000/` and all worked fine. Chrome / Win7 x64. What is exactly the problem you have?

**Comment by hhzl** [comment]
In ``devel`` mode (master branch) it works fine.

The problem is with the gh-1 https://github.com/hhzl/trysmalltalk0142/tree/gh-1 when I  do the following.

1. ``grunt deploy``
2. Copy the files ``index.html`` and ``the.js`` to a ``distribution`` directory.
3. Open ``index.html``.

then the ``codemirror/lib/codemirror`` error mentioned above appears. 

this is on Linux Mint 17, FF34.

**Comment by herby** [comment]
Fixed by amber-smalltalk/amber-attic@19847685ab242ec7b63b8bc89a0bbe9bdad19855.

**Comment by hhzl** [comment]
After fix by Herby https://github.com/amber-smalltalk/amber-attic/commit/4aa2b2889b7c8f9c44538aff8246fa70c2f57b90 release 0.1.2. and

    bower install amber-attic --save

the TrySmalltalkWidget appears in deployment mode (``index.html`` plus ``the.js``) which it did _not_ before.

However executing Amber commands ("do-it" or "print-it") still does not work.

**Comment by herby** [comment]
@hhzl Close this and create new one for Ctrl-D (I am not sure if Ctrl-P also had a problem, i recall it worked)?

**Comment by hhzl** [comment]
It is not only limited to Ctrl-D not working.  The buttons do not work either.

See https://github.com/hhzl/trysmalltalk0142/issues/1 for test with inclusion of 
https://github.com/amber-smalltalk/amber-attic/commit/4aa2b2889b7c8f9c44538aff8246fa70c2f57b90
